export const USER_LOGIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_SIGNIN_FAIL";
<<<<<<< HEAD
export const BASE_URL = "http://localhost:4000";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
=======
export const BASE_URL = "https://server-cellphones-8wsx.onrender.com";
>>>>>>> a0e4353579f6cb22e693e110f78edb9f9e799c41
